[[Graphene]]
arch = "x86_64"
git-tree-sha1 = "397dce3982524accaa6c28f0299d27e2015de4bd"
os = "macos"

    [[Graphene.download]]
    sha256 = "d5d48b1a22a162edd5d52c11856f13b76ef8ddd10c6e24a64d64df4f915fdfdc"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.0+1/Graphene.v1.10.0.x86_64-apple-darwin14.tar.gz"
[[Graphene]]
arch = "i686"
git-tree-sha1 = "86b81534b73c9943312b79f5ec4835c4530a787f"
libc = "glibc"
os = "linux"

    [[Graphene.download]]
    sha256 = "cb8b2fea5776e708e18bfa36496a53add49f0f13edcc2e747de11ad829a69cc6"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.0+1/Graphene.v1.10.0.i686-linux-gnu.tar.gz"
[[Graphene]]
arch = "x86_64"
git-tree-sha1 = "0c7dfd0ee77752624ced47c02170a76c99430ad7"
os = "freebsd"

    [[Graphene.download]]
    sha256 = "e5ef9a8aeb337fd6d82fdc68fd8904c805d66fac7d6e966dec957d4b6ffbd816"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.0+1/Graphene.v1.10.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Graphene]]
arch = "powerpc64le"
git-tree-sha1 = "403f0489b8e743aa3d9a1b40febfa68600ae360f"
libc = "glibc"
os = "linux"

    [[Graphene.download]]
    sha256 = "c125c602b279e408e898d443228b78cb6e5471b5a93869d996f75713a16e7417"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.0+1/Graphene.v1.10.0.powerpc64le-linux-gnu.tar.gz"
[[Graphene]]
arch = "x86_64"
git-tree-sha1 = "96555577cee1db80305a521ed123efb07dd34fe4"
libc = "musl"
os = "linux"

    [[Graphene.download]]
    sha256 = "47b4cb6b7f9b07a6015f8d907db1bfb7dba0dcb242de3bd20ecb46f6375a1b68"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.0+1/Graphene.v1.10.0.x86_64-linux-musl.tar.gz"
[[Graphene]]
arch = "x86_64"
git-tree-sha1 = "1a982d619bf9187fc3666f3a34dddd94120208fb"
libc = "glibc"
os = "linux"

    [[Graphene.download]]
    sha256 = "e66a788f5348e1a98f2ac7e412e842db1eb459a2e04d2ec426183952a46c167e"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.0+1/Graphene.v1.10.0.x86_64-linux-gnu.tar.gz"
[[Graphene]]
arch = "x86_64"
git-tree-sha1 = "a3d71281dbbd0d12de1a165bea762330f7ce83fe"
os = "windows"

    [[Graphene.download]]
    sha256 = "c9487ca181cdb470251707624d6a31aeb80762dd85beadc789c1831da7b33ec2"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.0+1/Graphene.v1.10.0.x86_64-w64-mingw32.tar.gz"
[[Graphene]]
arch = "aarch64"
git-tree-sha1 = "f1c35167342b934635d41c930ac5a7add177b669"
libc = "musl"
os = "linux"

    [[Graphene.download]]
    sha256 = "ddccd4b08ea49400618380c752270c2b3a118fb660f85a3faeb9dd17d6fe5127"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.0+1/Graphene.v1.10.0.aarch64-linux-musl.tar.gz"
[[Graphene]]
arch = "armv7l"
git-tree-sha1 = "dc01a253e52f876de8f3355edfa8ca2692e593b8"
libc = "glibc"
os = "linux"

    [[Graphene.download]]
    sha256 = "058ac3ada2607c95191794edc9e9540c1d60780266ec661fceae634259e0f738"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.0+1/Graphene.v1.10.0.arm-linux-gnueabihf.tar.gz"
[[Graphene]]
arch = "i686"
git-tree-sha1 = "d732ec6bdfb761b34fb0834697f9b20c86ebec74"
libc = "musl"
os = "linux"

    [[Graphene.download]]
    sha256 = "7465dfccf1af28312ab0519d7ab5b816c756f3c1689033e3e764aa630019a6ec"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.0+1/Graphene.v1.10.0.i686-linux-musl.tar.gz"
[[Graphene]]
arch = "armv7l"
git-tree-sha1 = "54adb3b989cef539ca32c06221d99df6b58b969f"
libc = "musl"
os = "linux"

    [[Graphene.download]]
    sha256 = "d3b3b4929129f8a0da1ad88fb2173d5e897c1e7e75794de35b2aeb3f0a50151f"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.0+1/Graphene.v1.10.0.arm-linux-musleabihf.tar.gz"
[[Graphene]]
arch = "aarch64"
git-tree-sha1 = "20ce991b9d879611877b1886f48629e37f09bbb2"
libc = "glibc"
os = "linux"

    [[Graphene.download]]
    sha256 = "ce397e39ddf1b707b86e9c9e07e264831433a1145f1ddebe4e0645c7e9f8338d"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.0+1/Graphene.v1.10.0.aarch64-linux-gnu.tar.gz"
[[Graphene]]
arch = "i686"
git-tree-sha1 = "bb9fdf747c0b050bba0331c084913ed77d95d37b"
os = "windows"

    [[Graphene.download]]
    sha256 = "e17f79a7fc1e6f96a727e2817228d11bd3b84fedbdaf803ed5ec5a1d40710d54"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.0+1/Graphene.v1.10.0.i686-w64-mingw32.tar.gz"
